name: Arduino Library CI

on: [pull_request, push, repository_dispatch]

jobs:
  pylint:
    runs-on: ubuntu-latest
#    needs: build
    steps:
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Versions
      run: |
        python3 --version
    - name: Pip install pylint, black, & Sphinx
      run: |
        pip install --force-reinstall pylint==1.9.2
    - name: Checkout Current Repo
      uses: actions/checkout@v2

    - name: lint
      run: ./pylint_check.sh

#  build:
#    strategy:
#      fail-fast: false
#      matrix:
#        arduino-platform: ["uno", "cpx_ada", "pyportal"]
#
#    runs-on: ubuntu-latest
#    
#    steps:
#    - uses: actions/setup-python@v1
#      with:
#        python-version: '3.x'
#    - uses: actions/checkout@v2
#    - uses: actions/checkout@v2
#      with:
#         repository: adafruit/ci-arduino
#         path: ci
#
#    - name: pre-install
#      run: bash ci/actions_install.sh
#
#    - name: test platforms
#      run: python3 ci/build_platform.py ${{ matrix.arduino-platform }}
#